vim.g.mapleader = " "
vim.g.maplocalleader = " "

local opt = vim.opt

opt.mouse = "a"                -- Enable mouse mode
opt.number = true              -- Print line number
opt.relativenumber = true      -- Relative line numbers
opt.clipboard = "unnamedplus"  -- Sync with system clipboard
opt.confirm = true             -- Confirm to save changes before exiting modified buffer
opt.cursorline = false          -- Enable highlighting of the current line
opt.expandtab = true           -- Use spaces instead of tabs
opt.shiftwidth = 2             -- Size of an indent
opt.tabstop = 2                -- Number of spaces tabs count for
opt.scrolloff = 4              -- Lines of context
opt.ignorecase = true          -- Ignore case
opt.sidescrolloff = 8          -- Columns of context
opt.signcolumn = "yes"         -- Always show the signcolumn, otherwise it would shift the text each time
opt.smartcase = true           -- Don't ignore case with capitals
opt.smartindent = true         -- Insert indents automatically
opt.splitbelow = true          -- Put new windows below current
opt.splitright = true          -- Put new windows right of current
opt.termguicolors = true       -- True color support
opt.wrap = false               -- Disable line wrap
opt.list = false               -- Show some invisible characters (tabs...
opt.laststatus = 3             -- the always show one statusline
opt.autoread = true            -- when file was modified, automatically read again
opt.textwidth = 120
opt.colorcolumn = "+1"
