require("nvim-web-devicons").setup({})
require("fzf-lua").setup({ fzf_colors = true })

local fzf = require("fzf-lua")
vim.keymap.set("n", "<leader><leader>", fzf.files)
vim.keymap.set("n", "<leader>ff", fzf.files)
vim.keymap.set("n", "<leader>fc", function()
	require("fzf-lua").files({ cwd = "~/.config/nvim" })
end)
vim.keymap.set("n", "<leader>sh", fzf.help_tags)
vim.keymap.set("n", "<leader>sk", fzf.keymaps)
vim.keymap.set("n", "<leader>sd", fzf.lsp_workspace_diagnostics)
vim.keymap.set("n", "<leader>/", fzf.grep)
vim.keymap.set("n", "<leader>,", fzf.buffers)
